<?php

namespace OiLab\OiLaravelNotes\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Model;
use OiLab\OiLaravelNotes\Models\Note;
use OiLab\OiLaravelNotes\OiNotes;

/**
 * Factory for generating Note model instances.
 *
 * @extends Factory<Note>
 */
class NoteFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return class-string
     */
    public function modelName(): string
    {
        return OiNotes::noteModel();
    }

    /**
     * Define the model's default state.
     *
     * By default the note is both authored by and attached to a freshly
     * created user. Use the `forNotable()` state to attach it elsewhere.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $userModel = OiNotes::userModel();

        return [
            'message' => $this->faker->sentence(),
            'has_bot' => false,
            'notable_type' => (new $userModel)->getMorphClass(),
            'notable_id' => $userModel::factory(),
            'user_id' => $userModel::factory(),
        ];
    }

    /**
     * Attach the note to a specific notable model.
     */
    public function forNotable(Model $notable): static
    {
        return $this->state(fn (array $attributes): array => [
            'notable_type' => $notable->getMorphClass(),
            'notable_id' => $notable->getKey(),
        ]);
    }

    /**
     * Mark the note as generated by an automated process, with no author.
     */
    public function byBot(): static
    {
        return $this->state(fn (array $attributes): array => [
            'has_bot' => true,
            'user_id' => null,
        ]);
    }
}
