<?php

namespace OiLab\OiLaravelNotes\Models;

use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use OiLab\OiLaravelAttachments\Concerns\HasAttachments;
use OiLab\OiLaravelNotes\Data\NoteData;
use OiLab\OiLaravelNotes\Database\Factories\NoteFactory;
use OiLab\OiLaravelNotes\Observers\NoteObserver;
use OiLab\OiLaravelNotes\OiNotes;

/**
 * Note Model
 *
 * Polymorphic note that can be attached to any notable model, optionally
 * authored by a user and enriched with file attachments.
 *
 * @property int $id Primary key
 * @property string $uuid Unique identifier (UUID v4)
 * @property string $message The note body
 * @property bool $has_bot Whether the note was generated by an automated process
 * @property string $notable_type Type of the parent model (polymorphic)
 * @property int $notable_id ID of the parent model (polymorphic)
 * @property int|null $user_id Foreign key to the authoring user
 */
#[ObservedBy(NoteObserver::class)]
class Note extends Model
{
    use HasAttachments;

    /** @use HasFactory<NoteFactory> */
    use HasFactory;

    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'uuid',
        'message',
        'has_bot',
        'notable_type',
        'notable_id',
        'user_id',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'has_bot' => 'boolean',
        'notable_id' => 'integer',
        'user_id' => 'integer',
    ];

    /**
     * Create a new factory instance for the model.
     */
    protected static function newFactory(): Factory
    {
        return NoteFactory::new();
    }

    /**
     * Get a data transfer object representing this note.
     */
    public function toData(): NoteData
    {
        return NoteData::from($this->toArray());
    }

    /**
     * Get the parent notable model.
     *
     * @return MorphTo<Model, $this>
     */
    public function notable(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * Get the user who authored this note.
     *
     * @return BelongsTo<Model, $this>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(OiNotes::userModel());
    }
}
